documentdb:
  database: treeherder-proxy-production

config:
  documentkey: production
  # always load the latest production-branches.json at startup
  projectsYmlUrl: https://hg.mozilla.org/build/ci-configuration/raw-file/tip/projects.yml
  files:
    - production-treeherder-proxy.yml

treeherderActions:
  exchange: exchange/treeherder/v1/job-actions
  queue: mozilla-taskcluster-production-actions

treeherderTaskcluster:
  routePrefix: tc-treeherder
  queue: mozilla-taskcluster-production

kue:
  purgeCompleted: true
  prefix: production
