documentdb:
  database: treeherder-proxy-stage

treeherderActions:
  exchange: exchange/treeherder-stage/v1/job-actions
  queue: mozilla-taskcluster-stage-actions

config:
  documentkey: stage
  files:
    - stage-treeherder-proxy.yml

treeherderTaskcluster:
  routePrefix: tc-treeherder-stage
  queue: mozilla-taskcluster-stage

kue:
  purgeCompleted: true
  prefix: stage

# Disable try functionality on staging configs the production
# version for now creates all task graphs...
try:
  enabled: true
