documentdb:
  database: treeherder-proxy-testing

treeherderActions:
  exchange: tests/treeherder-job-actions
  connectionString: just-testing


kue:
  prefix: test
  logFailedJobs: true

repositoryMonitor:
  interval: 1000
  maxPushFetches: 100

treeherderTaskcluster:
  routePrefix: tc-treeherder-test
  connectionString: just-testing

commitPublisher:
  exchangePrefix: tests/
  connectionString: just-testing

treeherder:
  credentials:
    clientId: 'my-client-id'
    secret: 'secret'

try:
  projects:
    testbranch:
      level: 7
      scopes: ['xyz']
