documentdb:
  database: treeherder-proxy-testing

treeherderActions:
  exchange: tests/treeherder-job-actions

config:
  files:
    - test-treeherder-proxy.yml
    - test/config.yml
kue:
  prefix: test
  logFailedJobs: true

repositoryMonitor:
  interval: 1000
  maxPushFetches: 100

treeherderTaskcluster:
  routePrefix: tc-treeherder-test

commitPublisher:
  exchangePrefix: tests/

treeherder:
  credentials:
    clientId: 'my-client-id',
    secret: 'secret'

try:
  projects:
    try:
      scopes:
        - queue:route:test*
        - scheduler:create-task-graph
        - queue:create-task:test/test
        - queue:define-task:test/test
        - queue:claim-task
        - assume:worker-type:test/test
        - assume:worker-id:test/test
        - queue:report-task-completed
        - queue:resolve-task
        - queue:route:tc-treeherder-test.*
